### ISSUE TITLE
What file do i need to prepair?

### ISSUE THREAD

**Issue by mcdoyaji** [gilir/rpi-mastodon#1]
I see [official guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md).

And It tells other files. For example, rakefile(and /config/appplication...), env.production.... etc.

I'm confused. Is there a easy way?

like...

1. clone all official mastodon.
2. clond all rpi-mastodon into previous one.
3. overwrite docker files.
4. do the same as reference guide.

**Comment by gilir** [comment]
To be short, you have to : 
- Create a directory
- Copy .env.production.sample from github into .env.production in this directory
- Change the settings in .env.production
- Add a docker-compose.yml. You can use the one upstream, and replace the images to use rpi ones (armhf/postgres:9.6-alpine for db, armhf/redis for redis, gilir/rpi-mastodon for gargron/mastodon).
- run "docker-compose run --rm web rake secret" 3 times to generate the 3 secret code, and copy them into .env.production
- run "docker-compose run --rm web rake db:migrate"
- run "docker-compose run --rm web rake assets:precompile"
- finaly, run "docker-compose up -d" to launch the services

I'll try to make a bit more documentation on the README.md, but all the recommendation of the official documentation should apply to this image.

**Comment by gilir** [comment]
I added a "How to use" section in the README.md : https://github.com/gilir/rpi-mastodon#how-to-use
With the new version of the image, it should be easier to start.
