### ISSUE TITLE
Erreur 404 !

### ISSUE THREAD

**Issue by rvlta** [gilir/rpi-mastodon#3]
Salut Gilir !

Le site pour télécharger l'image est innaccessible. J'aimerais savoir si c'est temporaire ou définitf. 
Si c'est définitif, où puis-je trouver une image adapté à l'architecture arm ? Je n'ai pas réussi à trouver pour le moment.

A bientot et merci !

**Comment by gilir** [comment]
Bonjour,
Merci pour le rappel :-) Oui le site a changé, j'ai mis à jour les informations sur ce mirroir que j'avais oublié.
