### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by rvlta** [gilir/rpi-mastodon#4]
Bonjour,

j'essai d'installer mastodon sur une Tinkerboard, avec Armbian. 

`docker-compose build` 
me donne

`redis uses an image, skipping
db uses an image, skipping
web uses an image, skipping`

Mais 
`docker-compose run --rm web rake secret`
me renvoi
`standard_init_linux.go:178: exec user process caused "exec format error"`

Je me demande si l'image (gilir/arm64-mastodon) est compatible avec ma configuration ? En effet il y a semaine avec la précédente image (gilir/rpi-mastodon) j'ai passé cette étape sans souci, sans finaliser l'installation. D'où mon interrogation. 

Si j'ai bien cherché l'architecture de la Tinkerboard est armv7l (qui serait du 32 bits), est-ce compatible avec l'image gilir/arm64-mastodon ?

A bientôt !

**Comment by gilir** [comment]
Bonjour,
Oui, l'image gilir/arm64-mastodon est compatible uniquement avec les configurations 64 bits. Je n'ai pour l'instant plus la possibilité de mettre à jour l'image 32 bits gilir/rpi-mastodon, j'espère pouvoir le faire dans les prochains jours / semaines.

**Comment by rvlta** [comment]
Salut ! 

Merci de ta réponse ! 
Mais j'ai testé ce matin avec l'image rpi-mastodon et cela a tout de même fonctionné !
Après un mois de labeur l'instance fonctionne également !

Merci pour tout !

Et bravo pour le travail effectué !

**Comment by rvlta** [comment]
Salut ! 

Merci de ta réponse ! 
Mais j'ai testé ce matin avec l'image rpi-mastodon et cela a tout de même fonctionné !
Après un mois de labeur l'instance fonctionne également !

Merci pour tout !

Et bravo pour le travail effectué !
