### ISSUE TITLE
Séparer données et logiciel

### ISSUE THREAD

**Issue by rvlta** [gilir/rpi-mastodon#5]
Bonjour,

j'suis sur une tinkerbard avec une carte SD de 64 G à laquel j'ai monté un disque dur de 1T.

J'aimerais installer les données sur le disque dur  et le logiciel sur la carte SD pour limiter l'écriture sur la carte SD. 
Je suis un amateur sans formation mais passionné, et j'ai des doutes quand à la bonne réalisation de cette manip.

Je suis suppose que tout ce passe dans le fichier docker-compose.yml dans la section 'volumes' seulement je ne sais pas à quoi correspondent les differents volumes ni comment les modifier.

Ma question est donc : 

Comment programmer l'installations des données sur le disque dur lors de l'installation ?

Merci  de votre lecture.

A bientôt

**Comment by gilir** [comment]
Bonjour,

Les volumes docker sont a créer avant de lancer les containers via docker-compose. C'est à ce moment là que l'on détermine où se trouvent les données. Pour plus d'information, vous pouvez lire la documentation des volumes dans Docker : https://docs.docker.com/storage/volumes/

Cependant, j'ai rajouté un commentaire dans docker-compose.yml pour créer rapidement des volumes correspondant à des répertoires de la machine locale : 
docker volume create --opt type=none --opt device=/path/to/data --opt o=bind --name name_of_the_volume

 Cette commande créera le volume "name_of_the_volume", dans le répertoire /path/to/data

Autre illustration : 
docker volume create --opt type=none --opt device=/srv/mastodon/log --opt o=bind --name mastodon_log

Cette commande créera le volume mastodon_log sur le répertoire /srv/mastodon/log

Il suffit alors de choisir des répertoires se trouvant sur le disque dur.

**Comment by rvlta** [comment]
Bonjour, et merci pour ces éclaircissements.

J'ai édité docker-compose.yml ainsi mais j'ai une question concernant les volumes présents dans les sections service: web: redis: db:
Est-ce que je dois les modifier aussi ou bien je ne modifie que la dernière section volumes: ?
> 
    web:
    restart: always
    build: .
    image: gilir/rpi-mastodon
    container_name: mastodon-web
    env_file: .env.production
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - redis
    networks:
      - proxy-network
    volumes:
      - mastodon_public_assets:/mastodon/public/assets
      - mastodon_public_packs:/mastodon/public/packs
      - mastodon_public_system:/mastodon/public/system
      - mastodon_log:/mastodon/log
    labels:
      - "traefik.docker.network=proxy-network"
      - "traefik.backend=mastodon-web"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:mastodon.lavergne.online"
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=5
      - SIDEKIQ_WORKERS=5
      - RUN_DB_MIGRATIONS=true
    networks:
      proxy-network:
         external:
           name: proxy-network
    volumes:
       mastodon_postgres:
            docker volume create --opt type=none --opt device=/media/DDE/mastodon/postgres --opt o=bind --name mastodon_postgres
      mastodon_redis:
            docker volume create --opt type=none --opt device=/media/DDE/mastodon/redis --opt o=bind --name mastodon_redis
      mastodon_public_assets:
           docker volume create --opt type=none --opt device=/media/DDE/mastodon/public/assets --opt o=bind --name mastodon_public_assets
      mastodon_public_system:
           docker volume create --opt type=none --opt device=/media/DDE/mastodon/public/system --opt o=bind --name mastodon_public_system
      mastodon_public_packs:
            docker volume create --opt type=none --opt device=/media/DDE/mastodon/public/packs --opt o=bind --name mastodon_public_packs
      mastodon_log:
            docker volume create --opt type=none --opt device=/media/DDE/mastodon/log --opt o=bind --name mastodon_log

**Comment by rvlta** [comment]
Bonjour,

tout d'abord, merci pour ton travail !

l'instance est en fonctionnement et à priori les volumes sont montés sur DDE. J'ai tout de même un problème pour téléverser des images sur le site. Mais là n'est pas le sujet de ce message.

J'ai bien fait les commandes avant de lancer les containers. Cependant quand j'ai lancé docker-compose, ce dernier reconnaissait les differents volumes comme 'external' sans à priori tenir compte des commande lancé auparavant et il m'était indiqué  de les créer  à cet instant. J'ai donc créé les volumes mais  avec la commande que tu as indiqué pendant l'installation : 

`docker volume create --opt type=none --opt device=/path/to/data --opt o=bind --name`

La subtilité était que le message de docker-compose me demandait simplement le nom et pas le chemin. J'ai donc complété avec ta commande.

As-tu un compte mastondon sur lequel te suivre ?

A bientôt et encore merci !
